# Generated by Django 3.2 on 2021-05-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordfrequency',
            name='visited',
        ),
    ]
